server:
  port: ${PORT:8080}

# The AWS Configurations
cloud:
  aws:
    credentials: 
      accessKey: 
      secretKey: 
      instanceProfile: true
      useDefaultAwsCredentialsChain: false
    region:
      auto: true
      static: us-east-1

# JSON formats and output rendition
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      INDENT_OUTPUT: true  